'use client';

import Box from '@mui/material/Box';

/**
 * Desktop product screenshot — edge-to-edge, dissolving into the page (editorial framing),
 * with a soft brand glow behind it. Office screenshots deliberately get NO device chrome:
 * framing a desktop UI in a laptop bezel makes a tool read as a consumer app, and the
 * whole category shows office screens bare. Phone captures use PhoneShot instead.
 *
 * Extracted 2026-09-11 from two near-identical inline copies — Hero's own <img> and a
 * local `FramelessShot` inside the old Features.tsx — which had drifted apart in glow
 * inset, blur radius and shadow. One recipe now, and one place to add srcset.
 *
 * WHY <picture> AND <img> ARE RAW ELEMENTS HERE rather than MUI <Box component="…">.
 * Two things go wrong if they are Boxes, and both were measured, not guessed:
 *
 *   1. Emotion injects a <style> tag immediately before the element it styles. Inside a
 *      <picture>, that lands BETWEEN the <source> and the <img> and breaks the picture's
 *      content model — Chromium fell back and fetched the 584 KB PNG *in addition to* the
 *      21 KB WebP it had already chosen. The whole optimisation was silently inverted.
 *   2. MUI's Box treats `width` and `height` as system style props, so they become CSS
 *      instead of HTML attributes and never reach the DOM. Without the attributes the
 *      browser cannot reserve the box, and every image on the page shifts layout as it
 *      decodes.
 *
 * So the img is styled from the wrapper with a descendant selector, which keeps the sx
 * ergonomics without putting Emotion inside <picture>.
 */
interface ScreenShotProps {
  src: string;
  alt: string;
  /** Fades the bottom edge into the page. Used by the hero, where the shot is cropped. */
  fade?: boolean;
  /** The one above-the-fold image. Everything else stays lazy. */
  priority?: boolean;
  width?: number;
  height?: number;
}

export default function ScreenShot({
  src,
  alt,
  fade = false,
  priority = false,
  width = 2880,
  height = 1800,
}: ScreenShotProps) {
  const webp = src.replace(/\.png$/, '.webp');
  const webp900 = src.replace(/\.png$/, '@900w.webp');
  // The media column is ~55% of an lg container on desktop and full-bleed below it.
  const sizes = '(min-width: 900px) 55vw, 100vw';

  return (
    <Box
      sx={{
        position: 'relative',
        '& img': {
          position: 'relative',
          zIndex: 1,
          display: 'block',
          width: '100%',
          height: 'auto',
          borderRadius: 2,
          border: '1px solid rgba(255,255,255,0.1)',
          boxShadow: '0 38px 85px -30px rgba(0,0,0,0.79)',
          ...(fade
            ? {
                maskImage: 'linear-gradient(to bottom, black 82%, transparent 100%)',
                WebkitMaskImage: 'linear-gradient(to bottom, black 82%, transparent 100%)',
              }
            : {}),
        },
      }}
    >
      <Box
        aria-hidden
        sx={{
          position: 'absolute',
          inset: '3% -5% -9% -3%',
          background: 'radial-gradient(closest-side, rgba(70,130,180,0.25), transparent)',
          filter: 'blur(54px)',
          zIndex: 0,
        }}
      />
      <picture>
        {/* WebP at the two widths this is actually drawn at; the PNG is the fallback src.
            Generated by scripts/optimizeMarketingImages.sh — see that file for why this is
            hand-rolled rather than next/image. */}
        <source type="image/webp" srcSet={`${webp900} 900w, ${webp} 1600w`} sizes={sizes} />
        <img
          src={src}
          alt={alt}
          width={width}
          height={height}
          loading={priority ? 'eager' : 'lazy'}
          fetchPriority={priority ? 'high' : undefined}
          decoding="async"
        />
      </picture>
    </Box>
  );
}
